const BIKES = [
  {
    id: "dominar400",
    name: "Dominar 400",
    category: "Cruiser",
    price: "₹2,32,040",
    cc: "373.3 cc",
    power: "40 bhp",
    mileage: "27 kmpl",
    tag: "Flagship",
    img: "images/bikes/dominar400/main.jpg",
    gallery: ["images/bikes/dominar400/main.jpg"],
    colors: ["Aurora Green", "Charcoal Black"],
    desc: "The ultimate hyper-riding machine. A 40 PS power cruiser built for long-distance touring."
  },
  {
    id: "dominar250",
    name: "Dominar 250",
    category: "Cruiser",
    price: "₹1,85,894",
    cc: "248.77 cc",
    power: "27 bhp",
    mileage: "35 kmpl",
    tag: "",
    img: "images/bikes/dominar250/main.jpg",
    gallery: ["images/bikes/dominar250/main.jpg"],
    colors: ["Racing Red", "Sparkling Black"],
    desc: "Sports touring made accessible. Liquid-cooled performance with a comfortable touring stance."
  },
  {
    id: "ns400z",
    name: "Pulsar NS400Z",
    category: "Sport",
    price: "₹1,85,000",
    cc: "349.13 cc",
    power: "40.04 bhp",
    mileage: "32 kmpl",
    tag: "New",
    img: "images/bikes/ns400z/main.jpg",
    gallery: ["images/bikes/ns400z/main.jpg"],
    colors: ["Pearl Metallic White", "Glossy Racing Red", "Brooklyn Black"],
    desc: "The most powerful Pulsar ever. Race-inspired streetfighter DNA with 40 PS on tap."
  },
  {
    id: "ns200",
    name: "Pulsar NS200",
    category: "Sport",
    price: "₹1,58,976",
    cc: "199.5 cc",
    power: "24.13 bhp",
    mileage: "36 kmpl",
    tag: "Popular",
    img: "images/bikes/ns200/main.jpg",
    gallery: ["images/bikes/ns200/main.jpg"],
    colors: ["Glossy Ebony Black"],
    desc: "The original street-sport icon with twin-projector LED headlamps."
  },
  {
    id: "n250",
    name: "Pulsar N250",
    category: "Sport",
    price: "₹1,51,910",
    cc: "249 cc",
    power: "24.1 bhp",
    mileage: "40 kmpl",
    tag: "",
    img: "images/bikes/n250/main.jpg",
    gallery: ["images/bikes/n250/main.jpg"],
    colors: ["Brooklyn Black", "Glossy Racing Red", "Pearl Metallic White"],
    desc: "Aggressive new-gen Pulsar with muscular tank and full-LED lighting."
  },
  {
    id: "ns160",
    name: "Pulsar NS160",
    category: "Sport",
    price: "₹1,46,801",
    cc: "160.3 cc",
    power: "17.03 bhp",
    mileage: "44 kmpl",
    tag: "Popular",
    img: "images/bikes/ns160/main.jpg",
    gallery: ["images/bikes/ns160/main.jpg"],
    colors: ["Pewter Grey", "Ebony Black", "Pearl Metallic White", "Cocktail Wine Red"],
    desc: "NS-series streetfighter with perimeter frame and sharp muscular styling."
  },
  {
    id: "pulsar220f",
    name: "Pulsar 220F",
    category: "Sport",
    price: "₹1,41,024",
    cc: "220 cc",
    power: "20.4 bhp",
    mileage: "40 kmpl",
    tag: "Legend",
    img: "images/bikes/pulsar220f/main.jpg",
    gallery: ["images/bikes/pulsar220f/main.jpg"],
    colors: ["Black Blue", "Black Red"],
    desc: "The legendary semi-faired Pulsar 220F with raw power and timeless styling."
  },
  {
    id: "n1604v",
    name: "Pulsar N160 4V",
    category: "Sport",
    price: "₹1,39,693",
    cc: "164.5 cc",
    power: "18.24 bhp",
    mileage: "49 kmpl",
    tag: "",
    img: "images/bikes/n160/main.jpg",
    gallery: ["images/bikes/n160/main.jpg"],
    colors: ["Atlantic Blue", "Pearl Metallic White", "Brooklyn Black"],
    desc: "4-valve N160 with stronger low-end torque and refined performance."
  },
  {
    id: "n160",
    name: "Pulsar N160 2V",
    category: "Sport",
    price: "₹1,22,966",
    cc: "164.82 cc",
    power: "15.68 bhp",
    mileage: "47 kmpl",
    tag: "Best Seller",
    img: "images/bikes/n160/main.jpg",
    gallery: ["images/bikes/n160/main.jpg"],
    colors: ["Atlantic Blue", "Pearl Metallic White", "Brooklyn Black"],
    desc: "Sharp, connected and powerful streetfighter with smartphone connectivity."
  },
  {
    id: "chetak",
    name: "Bajaj Chetak",
    category: "EV",
    price: "₹1,15,000",
    cc: "EV",
    power: "3.1 kW",
    mileage: "131 km",
    tag: "EV",
    img: "images/bikes/chetak/main.jpg",
    gallery: ["images/bikes/chetak/main.jpg"],
    colors: ["Brooklyn Black", "Cyber White", "Matte Coarse Grey"],
    desc: "Premium electric scooter with retro-modern style and long real-world range."
  },
  {
    id: "pulsar150",
    name: "Pulsar 150",
    category: "Commuter",
    price: "₹1,13,696",
    cc: "149.5 cc",
    power: "14 bhp",
    mileage: "47.5 kmpl",
    tag: "",
    img: "images/bikes/pulsar150/main.jpg",
    gallery: ["images/bikes/pulsar150/main.jpg"],
    colors: ["Red", "Black", "Blue"],
    desc: "Evergreen Pulsar 150 with trusted performance and outstanding value."
  },
  {
    id: "ns125",
    name: "Pulsar NS125",
    category: "Sport",
    price: "₹1,00,864",
    cc: "124.45 cc",
    power: "11.8 bhp",
    mileage: "50 kmpl",
    tag: "",
    img: "images/bikes/ns125/main.jpg",
    gallery: ["images/bikes/ns125/main.jpg"],
    colors: ["Black", "Orange"],
    desc: "NS-series DNA in a lighter, friendlier package."
  },
  {
    id: "n125",
    name: "Pulsar N125",
    category: "Commuter",
    price: "₹94,707",
    cc: "124.45 cc",
    power: "11.8 bhp",
    mileage: "58 kmpl",
    tag: "",
    img: "images/bikes/n125/main.jpg",
    gallery: ["images/bikes/n125/main.jpg"],
    colors: ["Ebony Black", "Cocktail Wine Red"],
    desc: "Modern commuter-sport Pulsar with great mileage."
  },
  {
    id: "pulsar125",
    name: "Pulsar 125",
    category: "Commuter",
    price: "₹92,883",
    cc: "124.4 cc",
    power: "11.8 bhp",
    mileage: "51.46 kmpl",
    tag: "Popular",
    img: "images/bikes/pulsar125/main.jpg",
    gallery: ["images/bikes/pulsar125/main.jpg"],
    colors: ["Red", "Black"],
    desc: "India's favourite Pulsar. Sporty commuter with high mileage."
  }
];

const OFFERS = [
  {
    id: "durgapuja",
    title: "Durga Puja Special Offer",
    sub: "Ride Karo, Jeeto Dil Khol Ke!",
    desc: "Buy any Bajaj bike and scratch your card to win exciting guaranteed prizes!",
    tag: "Mega Offer",
    gold: true,
    terms: "Guaranteed prize on every scratch card! Valid during Durga Puja."
  },
  {
    id: "emi",
    title: "0% Easy EMI",
    sub: "Starting at just ₹3,999/mo",
    desc: "Ride home today with flexible EMI plans and instant loan approval.",
    tag: "Finance",
    alt: true,
    terms: "Finance approval subject to bank norms & eligibility."
  },
  {
    id: "exchange",
    title: "Best Exchange Value",
    sub: "Extra Exchange Bonus",
    desc: "Trade in your old bike and get the best market value plus extra bonus.",
    tag: "Exchange",
    alt: true,
    terms: "Exchange value assessed at showroom."
  },
  {
    id: "gifts",
    title: "Free Helmet + Accessories",
    sub: "Worth ₹1,500",
    desc: "Every bike bought this month gets a free ISI helmet and accessories kit.",
    tag: "Gift",
    alt: false,
    terms: "One gift set per bike purchase. While stock lasts."
  }
];

const FULL_CATALOGUE = [
  { name: "Dominar 400", price: "₹2,32,040" },
  { name: "Dominar 250", price: "₹1,85,894" },
  { name: "Pulsar NS400Z", price: "₹1,85,000" },
  { name: "Pulsar RS200", price: "₹1,74,419" },
  { name: "Pulsar NS200", price: "₹1,58,976" },
  { name: "Pulsar N250", price: "₹1,51,910" },
  { name: "Pulsar NS160", price: "₹1,46,801" },
  { name: "Pulsar 220F", price: "₹1,41,024" },
  { name: "Pulsar N160 4V", price: "₹1,39,693" },
  { name: "Pulsar N160 2V", price: "₹1,22,966" },
  { name: "Avenger Cruise 220", price: "₹1,45,216" },
  { name: "Avenger Street 160", price: "₹1,19,456" },
  { name: "Chetak Premium", price: "₹1,27,244" },
  { name: "Chetak EV", price: "₹1,15,000" },
  { name: "Pulsar 150", price: "₹1,13,696" },
  { name: "Pulsar NS125", price: "₹1,00,864" },
  { name: "Freedom 125 CNG", price: "₹95,000" },
  { name: "Pulsar N125", price: "₹94,707" },
  { name: "Pulsar 125", price: "₹92,883" },
  { name: "Platina 110", price: "₹71,354" },
  { name: "CT 110X", price: "₹70,176" },
  { name: "Platina 100", price: "₹68,685" }
];
